[package]
name = "nx-nixos"
description = "NixOS system operations"
version.workspace = true
edition.workspace = true

[dependencies]
nx-core = { path = "../nx-core" }
clap.workspace = true
color-eyre.workspace = true
tracing.workspace = true
yansi.workspace = true
chrono = "0.4"
nix = { version = "0.31", features = ["user"] }
