name: Publish to nixpkgs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: false
        type: string
  push:
    tags:
      - "v*"

jobs:
  publish:
    uses: pawprnt/.github/.github/workflows/nix-publish.yml@main
    with:
      pkgname: nx
      nixpkgs-repo: pawprnt/nixpkgs
      nix-path: nix/default.nix
      version: ${{ inputs.version || github.ref_name }}
    secrets:
      NIX_GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
